detectors:
  IrresponsibleModule:
    enabled: false

  MissingSafeMethod:
    enabled: false

  UncommunicativeModuleName:
    enabled: false

directories:
  "app/controllers":
    InstanceVariableAssumption:
      enabled: false
