AllCops:
  Exclude:
    - 'Cheffile'
    - 'Vagrantfile'
    - 'config.ru'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'db/data/**/*'
    - 'db/migrate/**/*'
    - 'app/database_scripts/database_scripts/possibly_duplicated_journal_names.rb'
    - 'lib/taxt_id_translator.rb'
    - 'app/controllers/name_fields_controller.rb'
    - 'lib/taxt_id_translator.rb'
    - 'lib/taxt_converter.rb'

Rails:
  Enabled: true

Rails/DynamicFindBy:
  Whitelist: find_by_sql find_by_name find_by_names

Rails/FilePath:
  Enabled: false

# TODO we want to enable this when the database is ready for it.
Rails/HasManyOrHasOneDependent:
  Enabled: false

# TODO investigate if this would be useful.
Rails/InverseOf:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

# TODO investigate.
Rails/SkipsModelValidations:
  Enabled: false

Layout/AlignArray:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Layout/ClassStructure:
  Enabled: true

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: rails

Layout/IndentHash:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousOperator:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Performance/RedundantMerge:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/Alias:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/AsciiComments:
  Enabled: false

Style/Attr:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  EnforcedStyle: is_a?

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/GuardClause:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Metrics/AbcSize:
  Max: 92

Metrics/BlockLength:
  Max: 337

Metrics/ClassLength:
  Max: 203

Metrics/CyclomaticComplexity:
  Max: 53

Metrics/MethodLength:
  Max: 111

Metrics/ModuleLength:
  Max: 113

Metrics/PerceivedComplexity:
  Max: 21

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 213
