language: ruby
cache: bundler
dist: bionic

rvm:
  - 2.6.5

bundler_args: --without development doc --deployment --jobs=3 --retry=3

before_install:
  - gem update --system 2.6.4
  - gem --version

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
  - cp config/server.yml.example config/server.yml

script:
  - bundle exec rubocop
  - RAILS_ENV=test bundle exec rake db:create
  - bundle exec cucumber --order random
  - bundle exec rspec spec --tag ~pending --order rand

services:
  - mysql
