swagger: '2.0'

info:
  version: "1.0.0"
  title: ANTCAT Rest API
  description: Read only API to access antcat.org
  contact: 
    name: Joe Russack
    email: JRussack@calacademy.org

#host: antcat.org
host: localhost:3000
#basePath: /v0.1
schemes: [http]
consumes: [application/json]
produces: [application/json]



paths:
  /v1/taxa/{id}:
    get:
      summary: Get a single taxon
      operationId: getTaxon
      tags:
        - taxon
      parameters:
        - name: id
          in: path
          description: taxon id
          required: true
          type: integer
          format: int32
      responses:
        "200":
          description: a single taxon record
          schema:
            $ref: '#/definitions/Taxon'
        "404":
          description: Record not found

  /v1/taxa/search/{string}:
    get:
      summary: Search taxa using advanced search string
      operationId: searchTaxa
      tags:
        - taxa
        - search
      parameters:
        - name: string
          in: path
          description: Advanced search string
          required: true
          type: string
      responses:
        "200":
          description: matching taxa records
          schema:
            $ref: '#/definitions/Taxa'
        "404":
          description: Record not found

  /v1/taxa:
    get:
      summary: Get taxa
      operationId: getTaxa
      tags:
        - taxa
      parameters:
        - name: starts_at
          in: query
          description: Lowest taxon ID to be returned
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: Returns 100 taxa at a time starting at an arbitrary taxon id. If no id is supplied, starts at zero
          schema:
            $ref: '#/definitions/Taxon'
        "404":
          description: Record not found

  /v1/protonyms:
    get:
      summary: Get all protonyms
      operationId: getProtonyms
      tags:
        - protonyms
        - protonym
      responses:
        "200":
          description: the first hundred citation records.
          schema:
            $ref: '#/definitions/Protonym'
        "404":
          description: Record not found

  /v1/protonyms/{id}:
    get:
      summary: Get a protonym
      operationId: getProtonym
      tags:
        - protonym
      parameters:
        - name: id
          in: path
          description: protonym id
          required: true
          type: integer
          format: int32
      responses:
        "200":
          description: a single protonym record
          schema:
            $ref: '#/definitions/Protonym'
        "404":
          description: Record not found

  /v1/authors/{id}:
    get:
      summary: Get an author
      operationId: getAuthor
      tags:
        - authors
      parameters:
        - name: id
          in: path
          description: author id
          required: true
          type: integer
          format: int32
      responses:
        "200":
          description: a single author record
          schema:
            $ref: '#/definitions/Author'
        "404":
          description: Record not found

  /v1/authors:
    get:
      summary: Get all authors
      operationId: getAuthors
      tags:
        - authors

      responses:
        "200":
          description: Array of Ids of all authors and their create/update dates
          schema:
            $ref: '#/definitions/Author'
        "404":
          description: Record not found


  /v1/author_names/{id}:
    get:
      summary: Get an author name by author id
      operationId: getAuthorName
      tags:
        - author_names
      parameters:
        - name: id
          in: path
          description: author id (not author NAME id!)
          required: true
          type: integer
          format: int32
      responses:
        "200":
          description: a single author name record
          schema:
            $ref: '#/definitions/AuthorName'
        "404":
          description: Record not found

  /v1/author_names:
    get:
      summary: Get all author names
      operationId: getAuthorNames
      tags:
        - authors

      responses:
        "200":
          description: Array of all author names
          schema:
            $ref: '#/definitions/AuthorName'
        "404":
          description: Record not found

  /v1/names/{id}:
    get:
      summary: Get an author name by author id
      operationId: getName
      tags:
        - name
      parameters:
        - name: id
          in: path
          description: name id
          required: true
          type: integer
          format: int32
      responses:
        "200":
          description: a single taxon name record
          schema:
            $ref: '#/definitions/Name'
        "404":
          description: Record not found

  /v1/names:
    get:
      summary: returns a maximum of 100 taxon names
      operationId: getNames
      tags:
        - names
        - name
      parameters:
        - name: starts_at
          in: query
          description: Lowest name ID to be returned
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: Array of all author names
          schema:
            $ref: '#/definitions/AuthorName'
        "404":
          description: Record not found

  /v1/citations:
    get:
      summary: Get all citations
      operationId: getCitations
      tags:
        - citations
        - citation
      parameters:
          - name: starts_at
            in: query
            description: Lowest citation ID to be returned
            required: false
            type: integer
            format: int32
      responses:
        "200":
          description: Returns 100 citations at a time starting at an arbitrary citation id. If no id is supplied, starts at zero

          schema:
            $ref: '#/definitions/Citation'
        "404":
          description: Record not found

  /v1/citations/{id}:
    get:
      summary: Get a citation
      operationId: getCitation
      tags:
        - citation
      parameters:
        - name: id
          in: path
          description: citation id
          required: true
          type: integer
          format: int32
      responses:
        "200":
          description: a single citation record
          schema:
            $ref: '#/definitions/Citation'
        "404":
          description: Record not found

  /v1/taxon_history_items:
    get:
      summary: Get all taxon_history_items
      operationId: getTaxonHistoryItems
      tags:
        - getTaxonHistoryItems
        - getTaxonHistoryItem
      parameters:
          - name: starts_at
            in: query
            description: Lowest taxon_history_item id to be returned
            required: false
            type: integer
            format: int32
      responses:
        "200":
          description: Returns 100 citations at a time starting at an arbitrary taxon_history_item_id id. If no id is supplied, starts at zero

          schema:
            $ref: '#/definitions/Citation'
        "404":
          description: Record not found

  /v1/taxon_history_items/{id}:
    get:
      summary: Get a single taxon_history_item
      operationId: getTaxonHistoryItem
      tags:
        - getTaxonHistoryItem
      parameters:
        - name: id
          in: path
          description: getTaxonHistoryItem id
          required: true
          type: integer
          format: int32
      responses:
        "200":
          description: a single getTaxonHistoryItem  record
          schema:
            $ref: '#/definitions/TaxonHistoryItem'
        "404":
          description: Record not found

#journal
#place
#publisher
#reference
#reference_author_name
#reference_document
#reference_section
#synonym
#taxon_history_item





definitions:
  Taxa:
    description: Abridged taxa records
    type: object
    properties:
      id:
        type: integer
        description: Antcat taxon id, primary key
      name:
        type: string
        description: de-normalized cache of the name object
  Taxon:
    description: Taxon level
    type: object
    properties:
      level:
        type: string
        description: Level of this particular taxon
        enum:
        - family
        - genus
        - species
        - subfamily
        - subgenus
        - subspecies
        - tribe
      body:
        type: object
        properties:
          id:
            type: integer
            description: Antcat taxon id, primary key
          created_at:
            type: string
            format: date-time
            description: Automatically generated timestamp for original creation
          updated_at:
            type: string
            format: date-time
            description: Automatically generated timestamp for most recent update
          fossil:
            type: boolean
            description: is it a fossil?
          status:
            type: string
            description: State (status of this record)
            enum:
            - valid
            - unidentifiable
            - excluded from Formicidae
            - homonym
            - unavailable
            - synonym
            - collective group name
            - obsolete combination
            - unavailable misspelling
            - original combination
            - unavailable uncategorized
          protonym_id:
            type: integer
            description: Id of the protonym record
          family_id:
            type: integer
            description: Only populated if this is a subfamily with a valid family
          subfamily_id:
            type: integer
            description: Populated for most records
          tribe_id:
            type: integer
            description: Only populated if this is a genus with a valid tribe.
          subgenus_id:
            type: integer
            description: Only populated if this is a species with a valid subgenus
          name_id:
            type: integer
            description: Link to the name record
          foo:
            type: integer
          homonym_replaced_by_id:
            type: integer
            description: Populated only if this is a homonym that has been superseded by another taxa.
          incertae_sedis_in:
            type: string
          type_taxt:
            type: string
          headline_notes_taxt:
            type: string
          hong:
            type: string
          type_name_id:
            type: integer
          genus_species_header_notes_taxt:
            type: string
          type_fossil:
            type: boolean
          name_cache:
            type: string
            description: de-normalized cache of the name object
          name_html_cache:
            type: string
            description: de-normalized cache of the name object in html format
          unresolved_homonym:
            type: boolean
          current_valid_taxon_id:
            type: integer
          ichnotaxon:
            type: string
          nomen_nudum:
            type: string
          verbatim_type_locality:
            type: string
          biogeographic_region:
            type: string
          type_specimen_repository:
            type: string
          type_specimen_code:
            type: string
          type_specimen_url:
            type: string
          collision_merge_id:
            type: integer
          auto_generated:
            type: boolean
            description: True if this was generated by an automatic import. Changed to false if a human has touched it.
          origin:
            type: string
            description: The origin of an automatic import. Remains populated even if an editor has touched it and turned the auto_generated flag to false.
          display:
            type: boolean
            description: True if it should be shown in the taxon browser. If false, it will still show in searches.




  Author:
    description: Author primary key IDs
    type: object
    properties:
      id:
        type: integer
        description: Antcat author id, primary key
      created_at:
        type: string
        format: date-time
        description: Automatically generated timestamp for original creation
      updated_at:
        type: string
        format: date-time
        description: Automatically generated timestamp for most recent update

  AuthorName:
    description: Author name record
    type: object
    properties:
      id:
        type: integer
        description: Antcat author name id, primary key
      author_id:
        type: integer
        description: FK to author
      name:
        type: string
        description: author name
      verified:
        type: boolean
      auto_generated:
        type: boolean
        description: Programatically generated (typically from an exteral import)
      origin:
        type: string
        description: If auto-generated, what was the origin of the data? This field can be populated even if "auto generated" is false, if it has been manually iudated inside of antcat. Otherwise nil.
      created_at:
        type: string
        format: date-time
        description: Automatically generated timestamp for original creation
      updated_at:
        type: string
        format: date-time
        description: Automatically generated timestamp for most recent update

  Protonym:
    description: Taxon protonym record
    type: object
    properties:
      id:
        type: integer
        description: Protonym id, primary key
      authorship_id:
        type: integer
        description: FK to author
      name_id:
        type: integer
        description: FK to name
      fossil:
        type: boolean
      locality:
        type: string
      auto_generated:
        type: boolean
        description: Programatically generated (typically from an exteral import)
      origin:
        type: string
        description: If auto-generated, what was the origin of the data? This field can be populated even if "auto generated" is false, if it has been manually iudated inside of antcat. Otherwise nil.
      created_at:
        type: string
        format: date-time
        description: Automatically generated timestamp for original creation
      updated_at:
        type: string
        format: date-time
        description: Automatically generated timestamp for most recent update

  Name:
    description: Taxon name
    type: object
    properties:
      id:
        type: integer
        description: Name id, primary key
      type:
        type: string
        description: Level of name
        enum:
        - FamilyOrSubfamilyName
        - SubtribeName
        - GenusName
        - OrderName
        - SpeciesName
        - TribeName
        - CollectiveGroupName
        - SubfamilyName
        - SubgenusName
        - SubspeciesName
      name:
        type: string
        description: Plain text name
      name_html:
        type: string
        description: html version of name (with formatting, usually italics)
      epithet:
        type: string
        description: Plain text terminal epithet
      epithet_html:
        type: string
        description: html version of terminal epithet (with formatting, usually italics)
      epithets:
        type: string
        description: all epithets, plain text
      protonym_html:
        type: string
        description: Populated only for valid protonyms.
      gender:
        type: string
        description: gender
        enum:
        - masculine
        - feninine
        - neuter
      nonconforming_name:
        type: boolean
        description: Names not confirming to standard naming conventions because they're archiac or erroneous.
      auto_generated:
        type: boolean
        description: Programatically generated (typically from an exteral import)
      origin:
        type: string
        description: If auto-generated, what was the origin of the data? This field can be populated even if "auto generated" is false, if it has been manually iudated inside of antcat. Otherwise nil.
      created_at:
        type: string
        format: date-time
        description: Automatically generated timestamp for original creation
      updated_at:
        type: string
        format: date-time
        description: Automatically generated timestamp for most recent update



  Citation:
    description: Citation
    type: object
    properties:
      id:
        type: integer
        description: Name id, primary key
      reference_id:
        type: integer
        description: fk to reference
      pages:
        type: string
        description: String describing the page range; no standard format
      notes_taxt:
        type: string
        description: Long field with text and notes
      auto_generated:
        type: boolean
        description: Programatically generated (typically from an exteral import)
      origin:
        type: string
        description: If auto-generated, what was the origin of the data? This field can be populated even if "auto generated" is false, if it has been manually iudated inside of antcat. Otherwise nil.
      created_at:
        type: string
        format: date-time
        description: Automatically generated timestamp for original creation
      updated_at:
        type: string
        format: date-time
        description: Automatically generated timestamp for most recent update

  TaxonHistoryItem:
    description: Taxon history element
    type: object
    properties:
      id:
        type: integer
        description: Name id, primary key
      taxon_id:
        type: integer
        description: fk to taxon
      position:
        type: integer
        description: relative priority of this particular taxon history item agsint others on this taxon
      taxt:
        type: string
        description: Long field with text and notes. Contains references to taxaon and reference ids with format {ref *}:.
      auto_generated:
        type: boolean
        description: Programatically generated (typically from an exteral import)
      origin:
        type: string
        description: If auto-generated, what was the origin of the data? This field can be populated even if "auto generated" is false, if it has been manually iudated inside of antcat. Otherwise nil.
      created_at:
        type: string
        format: date-time
        description: Automatically generated timestamp for original creation
      updated_at:
        type: string
        format: date-time
        description: Automatically generated timestamp for most recent update