swagger: '2.0'

info:
  version: "1.0.0"
  title: ANTCAT Rest API
  description: Read only API to access antcat.org
  contact: 
    name: Joe Russack
    email: JRussack@calacademy.org

#host: antcat.org
host: localhost:3000
#basePath: /v0.1
schemes: [http]
consumes: [application/json]
produces: [application/json]



paths:
  /v1/taxa/{id}:
    get:
      summary: Get a single taxon
      operationId: getTaxon
      tags:
        - taxa
      parameters:
        - name: id
          in: path
          description: taxon id
          required: true
          type: integer
          format: int32
      responses:
        "200":
          description: a single taxon record
          schema:
            $ref: '#/definitions/Taxon'
        "404":
          description: Record not found

  /v1/taxa/search/{string}:
    get:
      summary: Search taxa using advanced search string
      operationId: searchTaxa
      tags:
        - taxa
        - search
      parameters:
        - name: string
          in: path
          description: Advanced search string
          required: true
          type: string
      responses:
        "200":
          description: matching taxa records
          schema:
            $ref: '#/definitions/Taxa'
        "404":
          description: Record not found

  /v1/taxa:
    get:
      summary: Get all taxa
      operationId: getTaxa
      tags:
        - taxa
      responses:
        "200":
          description: Array of Ids and names of all taxa
          schema:
            $ref: '#/definitions/Taxa'
        "404":
          description: Record not found

  /v1/protonyms/{id}:
    get:
      summary: Get a ptotonym
      operationId: getProtonym
      tags:
        - protonyms
      parameters:
        - name: id
          in: path
          description: protonym id
          required: true
          type: integer
          format: int32
      responses:
        "200":
          description: a single protonym record
          schema:
            $ref: '#/definitions/Protonym'
        "404":
          description: Record not found

  /v1/authors/{id}:
    get:
      summary: Get an author
      operationId: getAuthor
      tags:
        - authors
      parameters:
        - name: id
          in: path
          description: author id
          required: true
          type: integer
          format: int32
      responses:
        "200":
          description: a single author record
          schema:
            $ref: '#/definitions/Author'
        "404":
          description: Record not found

  /v1/authors:
    get:
      summary: Get all authors
      operationId: getAuthors
      tags:
        - authors

      responses:
        "200":
          description: Array of Ids of all authors and their create/update dates
          schema:
            $ref: '#/definitions/Author'
        "404":
          description: Record not found


  /v1/author_names/{id}:
    get:
      summary: Get an author name
      operationId: getAuthorName
      tags:
        - author_names
      parameters:
        - name: id
          in: path
          description: author name id
          required: true
          type: integer
          format: int32
      responses:
        "200":
          description: a single author name record
          schema:
            $ref: '#/definitions/AuthorName'
        "404":
          description: Record not found

  /v1/author_names:
    get:
      summary: Get all author names
      operationId: getAuthorNames
      tags:
        - authors

      responses:
        "200":
          description: Array of all author names
          schema:
            $ref: '#/definitions/AuthorName'
        "404":
          description: Record not found

#citation
#journal
#place
#protonym
#publisher
#reference
#reference_author_name
#reference_document
#reference_section
#synonym
#taxon_history_item





definitions:
  Taxa:
    description: Abridged taxa records
    type: object
    properties:
      id:
        type: integer
        description: Antcat taxon id, primary key
      name:
        type: string
        description: de-normalized cache of the name object

  Taxon:
    description: Taxon level
    type: object
    properties:
      level:
        type: string
        description: Level of this particular taxon
        enum:
        - family
        - genus
        - species
        - subfamily
        - subgenus
        - subspecies
        - tribe
      body:
        type: object
        properties:
          id:
            type: integer
            description: Antcat taxon id, primary key
          created_at:
            type: string
            format: date-time
            description: Automatically generated timestamp for original creation
          updated_at:
            type: string
            format: date-time
            description: Automatically generated timestamp for most recent update
          fossil:
            type: boolean
            description: is it a fossil?
          status:
            type: string
            description: State (status of this record)
            enum:
            - valid
            - unidentifiable
            - excluded from Formicidae
            - homonym
            - unavailable
            - synonym
            - collective group name
            - obsolete combination
            - unavailable misspelling
            - original combination
            - unavailable uncategorized
          protonym_id:
            type: integer
            description: Id of the protonym record
          family_id:
            type: integer
            description: Only populated if this is a subfamily with a valid family
          subfamily_id:
            type: integer
            description: Populated for most records
          tribe_id:
            type: integer
            description: Only populated if this is a genus with a valid tribe.
          subgenus_id:
            type: integer
            description: Only populated if this is a species with a valid subgenus
          name_id:
            type: integer
            description: Link to the name record
          foo:
            type: integer
          homonym_replaced_by_id:
            type: integer
            description: Populated only if this is a homonym that has been superseded by another taxa.
          incertae_sedis_in:
            type: string
          type_taxt:
            type: string
          headline_notes_taxt:
            type: string
          hong:
            type: string
          type_name_id:
            type: integer
          genus_species_header_notes_taxt:
            type: string
          type_fossil:
            type: boolean
          name_cache:
            type: string
            description: de-normalized cache of the name object
          name_html_cache:
            type: string
            description: de-normalized cache of the name object in html format
          unresolved_homonym:
            type: boolean
          current_valid_taxon_id:
            type: integer
          ichnotaxon:
            type: string
          nomen_nudum:
            type: string
          verbatim_type_locality:
            type: string
          biogeographic_region:
            type: string
          type_specimen_repository:
            type: string
          type_specimen_code:
            type: string
          type_specimen_url:
            type: string
          collision_merge_id:
            type: integer
          auto_generated:
            type: boolean
            description: True if this was generated by an automatic import. Changed to false if a human has touched it.
          origin:
            type: string
            description: The origin of an automatic import. Remains populated even if an editor has touched it and turned the auto_generated flag to false.
          display:
            type: boolean
            description: True if it should be shown in the taxon browser. If false, it will still show in searches.


  Protonym:
    description: Taxon protonym
    type: object
    properties:
      id:
        type: integer
        description: Integer id, primary key
      created_at:
        type: string
        format: date-time
        description: Automatically generated timestamp for original creation
      updated_at:
        type: string
        format: date-time
        description: Automatically generated timestamp for most recent update

  Author:
    description: Author primary key IDs
    type: object
    properties:
      id:
        type: integer
        description: Antcat author id, primary key
      created_at:
        type: string
        format: date-time
        description: Automatically generated timestamp for original creation
      updated_at:
        type: string
        format: date-time
        description: Automatically generated timestamp for most recent update

  AuthorName:
    description: Author name record
    type: object
    properties:
      id:
        type: integer
        description: Antcat author name id, primary key
      author_id:
        type: integer
        description: FK to author
      name:
        type: string
        description: author name
      verified:
        type: boolean
      auto_generated:
        type: boolean
        description: Programatically generated (typically from an exteral import)
      source:
        type: string
        description: If auto-generated, what was the origin of the data? This field can be populated even if "auto generated" is false, if it has been manually iudated inside of antcat. Otherwise nil.
      created_at:
        type: string
        format: date-time
        description: Automatically generated timestamp for original creation
      updated_at:
        type: string
        format: date-time
        description: Automatically generated timestamp for most recent update









