production_url: "https://antcat.org"

http_basic_auth:
  enabled: false
  name:
  password:

catalog:
  # To make is easier to disable 'Fix Random!' in case of performance issues.
  show_failed_soft_validations: true

new_relic:
  apm_url: "https://example.com"

contact_us_email_address: "jrussack@calacademy.org"
suggest_edit_email_address: "bfisher@calacademy.org"
