production:
  solr:
    hostname: index.websolr.com
    port: 80
    path: <%=
      require 'milieu'
      $Milieu.preview? ? '/solr/86db0cc797f' : '/solr/ea8fcb74b3b'
    %>
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
